version: '3.8'

services:
  app:
    container_name: app
    image: app_image
    restart: always
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      app_db:
        condition: service_healthy

  app_db:
    image: postgres
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 20s
      retries: 5

volumes:
  app_pg_data:
    driver: "local"

#networks:
#  default:
#    external: true
#    name: app_main