"""add telegram_id

Revision ID: 55c36f31b02c
Revises: a67cfd250186
Create Date: 2023-08-15 17:30:23.046844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c36f31b02c'
down_revision: Union[str, None] = 'a67cfd250186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE posts ADD COLUMN telegram_id BIGINT NOT NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'telegram_id')
    # ### end Alembic commands ###
