"""optionals

Revision ID: ab09bf52ac41
Revises: ea5524a0dd9a
Create Date: 2023-08-14 19:49:41.022514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab09bf52ac41'
down_revision: Union[str, None] = 'ea5524a0dd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('posts', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('posts', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
